default:
	$(MAKE) all

all:
	$(MAKE) -C pi all
	$(MAKE) -C maximum all
	$(MAKE) -C mergesort all

clean:
	$(MAKE) -C pi clean
	$(MAKE) -C maximum clean
	$(MAKE) -C mergesort clean

test:
	$(MAKE) -C pi test
	$(MAKE) -C maximum test
	$(MAKE) -C mergesort test

depend:
	$(MAKE) -C pi depend
	$(MAKE) -C maximum depend
	$(MAKE) -C mergesort depend

