default:
	$(MAKE) all

all:
	$(MAKE) -C pi all
	$(MAKE) -C maximum all

clean:
	$(MAKE) -C pi clean
	$(MAKE) -C maximum clean

test:
	$(MAKE) -C pi test
	$(MAKE) -C maximum test

depend:
	$(MAKE) -C pi depend
	$(MAKE) -C maximum depend

