variables:
  DOCKER_IMAGE: rwthos/gi4

stages:
  - prepare
  - build
  - deploy

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE} -f docker/Dockerfile .
  tags:
    - shell
    - linux

# Stage: build
##############################################################################

build:
  stage: build
  script:
    - make
    - make test
  image: ${DOCKER_IMAGE}
  tags:
    - docker
# Stage: deploy
##############################################################################

deploy:docker:
  stage: deploy
  script:
    - docker push ${DOCKER_IMAGE}
  tags:
    - linux
    - shell
