default:
	$(MAKE) all

all:
	$(MAKE) -C pi all
	$(MAKE) -C maximum all
	$(MAKE) -C mergesort all
	$(MAKE) -C rounding_error all
	$(MAKE) -C strcpy all

clean:
	$(MAKE) -C pi clean
	$(MAKE) -C maximum clean
	$(MAKE) -C mergesort clean
	$(MAKE) -C rounding_error clean
	$(MAKE) -C strcpy clean

test:
	$(MAKE) -C pi test
	$(MAKE) -C maximum test
	$(MAKE) -C mergesort test
	$(MAKE) -C rounding_error test
	$(MAKE) -C strcpy test

depend:
	$(MAKE) -C pi depend
	$(MAKE) -C maximum depend
	$(MAKE) -C mergesort depend
	$(MAKE) -C rounding_error depend
	$(MAKE) -C strcpy depend

