default:
	$(MAKE) all

all:
	$(MAKE) -C v1 all
	$(MAKE) -C v2 all

clean:
	$(MAKE) -C v1 clean
	$(MAKE) -C v2 clean

test:
	$(MAKE) -C v1 test
	$(MAKE) -C v2 test

depend:
	$(MAKE) -C v1 depend
	$(MAKE) -C v2 depend
